require_relative 'house/house.rb'
require_relative 'house/satchel.rb'
require_relative 'house/monster.rb'
require_relative 'house/item.rb'
require_relative 'house/room.rb'
require_relative 'house/player.rb'
require_relative 'house/game.rb'